config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "homes" => "homes#top"
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new(book_params)
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
      flash[:alert] = 'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to books_path
       flash[:alert] = "Book was successfully updated."
    else
      render :edit

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
    flash[:alert] = "Book was successfully destroyed"
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
<div class="error_explanation">
  <h2><%=@book.errors.count %>
  errors prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= form_with model: @book do |f| %>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
<div class="edit-up">
  <%= f.submit 'Update Book' %>
</div>
<br>
<div class="edit-sb">
  <%= link_to "Show", book_path(@book.id)%>
|
  <%= link_to "Back", books_path%>
</div>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
<table width="700">
  <thead>
    <tr>
      <th width="25%">Title</th>
      <th width="50%">Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @books.each do |book| %>
    <tr>
      <th><%=book.title%></th>
      <td><%=book.body%></td>
      <td><%=link_to "Show", book_path(book)%></td>
      <td><%=link_to "Edit", edit_book_path(book)%></td>
      <td><%=link_to "Destroy", book_path(book),method: :delete, "data-confirm" => "Are you sure?"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<h2>New book</h2>
<% if @book.errors.any? %>
  <div class ="error_explanation">
    <h2><%= @book.errors.count %>
    errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model: @book do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
 </div>
 <br>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<% if @book.errors.any? %>
    <%= @book.errors.count %>
      <ul>
        <% @book.errors.full_messages.each do |message|%>
        <li><%= message%></li>
        <% end %>
      </ul>
  <% end %>
  <%= form_with model: @book do |f| %>
    <h4>title</h4>
    <%= f.text_field :title%>
    <h4>body</h4>
    <%= f.text_area :body%>
    <br><%= f.submit "Create Book"%>
  <% end %>

app/views/books/show.html.erb
<div class="field-show">
  <laber for="book_title">Title:</laber>
  <%= @book.title %>
</div>
<div class="field-show">
  <laber for="book_body">Body:</laber>
  <%= @book.body %>
</div>

<span>
  <%= link_to "Edit", edit_book_path(@book.id)%>
</span>
|
  <%= link_to "Back", books_path%>

app/views/homes/top.html.erb
<h1>Bookesrでは新しい</h1>
　<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>B2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flash-m"><%= flash[:alert]  %></div>
    <%= yield %>
  </body>
</html>